### ISSUE TITLE
Needs Updating

### ISSUE THREAD

**Issue by hsyyid** [Dracade/Ember#2]
Two Issues:

* Uses `GUAVA`'s Optional rather than `Java`'s - Sponge uses's `Java`'s.
* Doesn't compile - errors with `getRunnable()` - no longer exists in SpongeAPI
* Uses `Location` rather than `Location<World>`
* Serializer/Deserializer may be broken [needs further testing]

**Comment by KieronWiltshire** [comment]
- I've updated from guava but haven't pushed.
- I'll take a look into that.
- I'm in the process of redeveloping the serializer/deserialiser.

**Comment by hsyyid** [comment]
@KieronWiltshire I updated it just enough for it to compile, and I cannot get it working.. I get a NullPointerException when I do `Ember.register(arena, this);` 

Error is here: http://pastebin.com/BvhtyPmy

**Comment by KieronWiltshire** [comment]
The npe seems to be coming from Ember.getArena

**Comment by hsyyid** [comment]
@KieronWiltshire Could it's task be null? Or the arenas HashMap?

**Comment by KieronWiltshire** [comment]
My guess is the task

**Comment by hsyyid** [comment]
@KieronWiltshire It was the actual HashMap.

**Comment by KieronWiltshire** [comment]
Haha so does it work now?

**Comment by hsyyid** [comment]
@KieronWiltshire  :cry: Nopes: http://pastebin.com/HAjWXNZU

**Comment by KieronWiltshire** [comment]
What's on deathmatchminigame line 68

**Comment by hsyyid** [comment]
@KieronWiltshire Haha, yeah that issue was my bad.

**Comment by hsyyid** [comment]
@KieronWiltshire http://pastebin.com/Fz9a42d8 - Think this one is Ember

**Comment by KieronWiltshire** [comment]
That's strange because that used to work haha

**Comment by hsyyid** [comment]
@KieronWiltshire I guess it changed? Anywho, I got it all working with my modified version, so cheers :smile:

**Comment by KieronWiltshire** [comment]
Commit it to GitHub?

**Comment by KieronWiltshire** [comment]
Fork and pull req

**Comment by hsyyid** [comment]
@KieronWiltshire kk
